CDO:
  image: "wjordan/code-dot-org:0.2"
  volumes:
    - .:/home/ubuntu/adhoc
  ports:
    - "3000:3000"
  environment:
    - RAILS_ENV=adhoc
    - RACK_ENV=adhoc
    - LANG=en_US.UTF-8
    - LANGUAGE=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  command: top -b
